cat("1. RESEARCH QUESTION:\n")
cat("   Does the mean proportion of COVID-19 cases among young adults (18-29 years)\n")
cat("   differ between early pandemic weeks (1-12) and later weeks (13-24) in Malaysia?\n\n")
cat("2. HYPOTHESES:\n")
cat("   Null Hypothesis (H₀): No difference in mean proportions between periods\n")
cat("   Alternative Hypothesis (H₁): Significant difference in mean proportions between periods\n\n")
cat("3. DATA SUMMARY:\n")
cat("   Dataset: COVID-19 case age distribution in Malaysia\n")
cat("   Time period: Weeks 1 to 24\n")
cat("   Age group analyzed: 18-29 years\n")
cat("   Total weeks analyzed:", nrow(df2), "\n")
cat("   - Early period (weeks 1-12):", sum(df2$period == "Early (1-12)"), "weeks\n")
cat("   - Later period (weeks 13-24):", sum(df2$period == "Later (13-24)"), "weeks\n\n")
cat("4. DESCRIPTIVE STATISTICS:\n")
cat("   " , strrep("-", 50), "\n")  
cat("   Statistic              Early (1-12)     Later (13-24)\n")
cat("   " , strrep("-", 50), "\n")
early_mean <- mean(df2$perc_18_29[df2$period == "Early (1-12)"])
later_mean <- mean(df2$perc_18_29[df2$period == "Later (13-24)"])
early_median <- median(df2$perc_18_29[df2$period == "Early (1-12)"])
later_median <- median(df2$perc_18_29[df2$period == "Later (13-24)"])
early_sd <- sd(df2$perc_18_29[df2$period == "Early (1-12)"])
later_sd <- sd(df2$perc_18_29[df2$period == "Later (13-24)"])
early_min <- min(df2$perc_18_29[df2$period == "Early (1-12)"])
later_min <- min(df2$perc_18_29[df2$period == "Later (13-24)"])
early_max <- max(df2$perc_18_29[df2$period == "Early (1-12)"])
later_max <- max(df2$perc_18_29[df2$period == "Later (13-24)"])
